/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BodaccCreationAllOf {
    /**
    * Nom de l\'entreprise concernée par la publication. Correspond à la dénomination en cas de personne morale et à nom + prenom en cas de personne physique.
    */
    'nomEntreprise'?: string;
    /**
    * Vrai si l\'entreprise concernée par la publication est une personne morale, faux si c\'est une personne physique.
    */
    'personneMorale'?: boolean;
    /**
    * Dénomination de l\'entreprise concernée par la publication (uniquement en cas de personne morale).
    */
    'denomination'?: string;
    /**
    * Nom de la personne physique concernée par la publication (uniquement en cas de personne physique).
    */
    'nom'?: string;
    /**
    * Prénom de la personne physique concernée par la publication (uniquement en cas de personne physique).
    */
    'prenom'?: string;
    /**
    * Administration (dans le cas d\'une personne morale).
    */
    'administration'?: string;
    /**
    * Adresse de l\'entreprise concernée par la publication.
    */
    'adresse'?: string;
    /**
    * Capital de l\'entreprise concernée par la publication.
    */
    'capital'?: number;
    /**
    * Activité de l\'entreprise concernée par la publication.
    */
    'activite'?: string;
    /**
    * Date de début d\'activité de l\'entreprise concernée par la publication, au format AAAA-MM-JJ.
    */
    'dateDebutActivite'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nomEntreprise",
            "baseName": "nom_entreprise",
            "type": "string"
        },
        {
            "name": "personneMorale",
            "baseName": "personne_morale",
            "type": "boolean"
        },
        {
            "name": "denomination",
            "baseName": "denomination",
            "type": "string"
        },
        {
            "name": "nom",
            "baseName": "nom",
            "type": "string"
        },
        {
            "name": "prenom",
            "baseName": "prenom",
            "type": "string"
        },
        {
            "name": "administration",
            "baseName": "administration",
            "type": "string"
        },
        {
            "name": "adresse",
            "baseName": "adresse",
            "type": "string"
        },
        {
            "name": "capital",
            "baseName": "capital",
            "type": "number"
        },
        {
            "name": "activite",
            "baseName": "activite",
            "type": "string"
        },
        {
            "name": "dateDebutActivite",
            "baseName": "date_debut_activite",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BodaccCreationAllOf.attributeTypeMap;
    }
}

