/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ComptesAnnuels200ResponseValueInnerSectionsInnerLiassesInnerColonnesInner } from './comptesAnnuels200ResponseValueInnerSectionsInnerLiassesInnerColonnesInner';

export class ComptesAnnuels200ResponseValueInnerSectionsInnerLiassesInner {
    /**
    * Code de la liasse.
    */
    'code'?: string;
    /**
    * Libellé de la liasse.
    */
    'libelle'?: string;
    /**
    * Colonnes de la liasse.
    */
    'colonnes'?: Array<ComptesAnnuels200ResponseValueInnerSectionsInnerLiassesInnerColonnesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "libelle",
            "baseName": "libelle",
            "type": "string"
        },
        {
            "name": "colonnes",
            "baseName": "colonnes",
            "type": "Array<ComptesAnnuels200ResponseValueInnerSectionsInnerLiassesInnerColonnesInner>"
        }    ];

    static getAttributeTypeMap() {
        return ComptesAnnuels200ResponseValueInnerSectionsInnerLiassesInner.attributeTypeMap;
    }
}

