/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EntrepriseFicheAllOfEvenements {
    /**
    * Type d\'événement.
    */
    'type'?: string;
    /**
    * Identifiant de l\'événement.
    */
    'identifiantEvenement'?: string;
    /**
    * Référence de l\'événement.
    */
    'reference'?: string;
    /**
    * Date de l\'événement, au format AAAA-MM-JJ.
    */
    'date'?: string;
    /**
    * Numéro du BOPI dans lequel l\'événement a été publié.
    */
    'numeroBopi'?: string;
    /**
    * Date de publication du BOPI au format AAAA-MM-JJ.
    */
    'dateBopi'?: string;
    /**
    * Bénéficiaire associé à l\'événement.
    */
    'beneficiaire'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "identifiantEvenement",
            "baseName": "identifiant_evenement",
            "type": "string"
        },
        {
            "name": "reference",
            "baseName": "reference",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "numeroBopi",
            "baseName": "numero_bopi",
            "type": "string"
        },
        {
            "name": "dateBopi",
            "baseName": "date_bopi",
            "type": "string"
        },
        {
            "name": "beneficiaire",
            "baseName": "beneficiaire",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntrepriseFicheAllOfEvenements.attributeTypeMap;
    }
}

