/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EntrepriseFicheAllOfDetailsPartsDirectes } from './entrepriseFicheAllOfDetailsPartsDirectes';
import { EntrepriseFicheAllOfDetailsPartsIndirectes } from './entrepriseFicheAllOfDetailsPartsIndirectes';
import { EntrepriseFicheAllOfDetailsPartsVocationTitulaire } from './entrepriseFicheAllOfDetailsPartsVocationTitulaire';
import { EntrepriseFicheAllOfDetailsSocieteDeGestion } from './entrepriseFicheAllOfDetailsSocieteDeGestion';
import { EntrepriseFicheAllOfDetailsVotesDirects } from './entrepriseFicheAllOfDetailsVotesDirects';
import { EntrepriseFicheAllOfDetailsVotesIndirects } from './entrepriseFicheAllOfDetailsVotesIndirects';

export class EntrepriseFicheAllOfBeneficiairesEffectifs {
    /**
    * Date de génération des bénéficiaires effectifs, au format AAAA-MM-JJ.
    */
    'dateGreffe'?: string;
    /**
    * Type du bénéficiaire effectif
    */
    'type'?: string;
    /**
    * Nom du bénéficiaire effectif.
    */
    'nom'?: string;
    /**
    * Nom d\'usage du bénéficiaire effectif.
    */
    'nomUsage'?: string;
    /**
    * Prénom du bénéficiaire effectif.
    */
    'prenom'?: string;
    'pseudonyme'?: string;
    /**
    * Mois et année de naissance du bénéficiaire effectif, au format MM/AAAA.
    */
    'dateDeNaissanceFormatee'?: string;
    /**
    * Date de naissance complète du bénéficiaire effectif, au format JJ/MM/AAAA.
    */
    'dateDeNaissanceCompleteFormatee'?: string;
    /**
    * Nationalité du bénéficiaire effectif.
    */
    'nationalite'?: string;
    /**
    * Code de la nationalité du bénéficiaire effectif.
    */
    'codeNationalite'?: string;
    /**
    * Ville de naissance du bénéficiaire effectif.
    */
    'villeDeNaissance'?: string;
    /**
    * Pays de naissance du bénéficiaire effectif.
    */
    'paysDeNaissance'?: string;
    /**
    * Code du pays de naissance du bénéficiaire effectif.
    */
    'codePaysDeNaissance'?: string;
    /**
    * Première ligne de l\'adresse du bénéficiaire effectif.
    */
    'adresseLigne1'?: string;
    /**
    * Deuxième ligne de l\'adresse du bénéficiaire effectif.
    */
    'adresseLigne2'?: string;
    /**
    * Troisième ligne de l\'adresse du bénéficiaire effectif.
    */
    'adresseLigne3'?: string;
    /**
    * Code postal du bénéficiaire effectif.
    */
    'codePostal'?: string;
    /**
    * Ville du bénéficiaire effectif.
    */
    'ville'?: string;
    /**
    * Pays du bénéficiaire effectif.
    */
    'pays'?: string;
    /**
    * Code du pays du bénéficiaire effectif.
    */
    'codePays'?: string;
    /**
    * Parts détenues par le bénéficiaire effectif, en pourcentage des parts totales.
    */
    'pourcentageParts'?: number;
    /**
    * Parts détenues de façon directe par le bénéficiaire effectif, en pourcentage des parts totales.
    */
    'pourcentagePartsDirectes'?: number;
    /**
    * Parts détenues de façon indirecte par le bénéficiaire effectif, en pourcentage des parts totales.
    */
    'pourcentagePartsIndirectes'?: number;
    /**
    * Parts dont le bénéficiaire effectif a vocation à devenir titulaire par l\'effet d\'un acte juridique, en pourcentage des parts totales.
    */
    'pourcentagePartsVocationTitulaire'?: number;
    'detailsPartsDirectes'?: EntrepriseFicheAllOfDetailsPartsDirectes;
    'detailsPartsIndirectes'?: EntrepriseFicheAllOfDetailsPartsIndirectes;
    'detailsPartsVocationTitulaire'?: EntrepriseFicheAllOfDetailsPartsVocationTitulaire;
    /**
    * Droits de vote détenus par le bénéficiaire effectif, en pourcentage des droits de vote totaux.
    */
    'pourcentageVotes'?: number;
    /**
    * Droits de vote détenus de façon directe par le bénéficiaire effectif, en pourcentage des droits de vote totaux.
    */
    'pourcentageVotesDirects'?: number;
    /**
    * Droits de vote détenus de façon indirecte par le bénéficiaire effectif, en pourcentage des droits de vote totaux.
    */
    'pourcentageVotesIndirect'?: number;
    'detailsVotesDirects'?: EntrepriseFicheAllOfDetailsVotesDirects;
    'detailsVotesIndirects'?: EntrepriseFicheAllOfDetailsVotesIndirects;
    'detailsSocieteDeGestion'?: EntrepriseFicheAllOfDetailsSocieteDeGestion;
    /**
    * Vaut vrai pour les moyens de contrôle sur les organes d\'administration, de gestion, de direction ou de surveillance de la personne morale autre que le pouvoir de nommer ou de révoquer la majorité des membres.
    */
    'detentionPouvoirDecisionAg'?: boolean;
    /**
    * Vaut vrai si le moyen de contrôle est le pouvoir de nommer ou de révoquer la majorité des membres des organes d\'administration, de gestion, de direction ou de surveillance de la personne morale.
    */
    'detentionPouvoirNomMembreConseilAdministration'?: boolean;
    /**
    * Vaut vrai s\'il existe d\'autres moyens de contrôle.
    */
    'detentionAutresMoyensControle'?: boolean;
    /**
    * Vaut vrai dans le cas où le bénéficiaire effectif a été défini comme le représentant légal par défaut.
    */
    'beneficiaireRepresentantLegal'?: boolean;
    /**
    * Vaut vrai dans le cas où le bénéficiaire effectif est le représentant légal du placement collectif (cas où le placement collectif n\'a pas délégué sa gestion à une société de gestion).
    */
    'representantLegalPlacementSansGestionDelegation'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateGreffe",
            "baseName": "date_greffe",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "nom",
            "baseName": "nom",
            "type": "string"
        },
        {
            "name": "nomUsage",
            "baseName": "nom_usage",
            "type": "string"
        },
        {
            "name": "prenom",
            "baseName": "prenom",
            "type": "string"
        },
        {
            "name": "pseudonyme",
            "baseName": "pseudonyme",
            "type": "string"
        },
        {
            "name": "dateDeNaissanceFormatee",
            "baseName": "date_de_naissance_formatee",
            "type": "string"
        },
        {
            "name": "dateDeNaissanceCompleteFormatee",
            "baseName": "date_de_naissance_complete_formatee",
            "type": "string"
        },
        {
            "name": "nationalite",
            "baseName": "nationalite",
            "type": "string"
        },
        {
            "name": "codeNationalite",
            "baseName": "code_nationalite",
            "type": "string"
        },
        {
            "name": "villeDeNaissance",
            "baseName": "ville_de_naissance",
            "type": "string"
        },
        {
            "name": "paysDeNaissance",
            "baseName": "pays_de_naissance",
            "type": "string"
        },
        {
            "name": "codePaysDeNaissance",
            "baseName": "code_pays_de_naissance",
            "type": "string"
        },
        {
            "name": "adresseLigne1",
            "baseName": "adresse_ligne_1",
            "type": "string"
        },
        {
            "name": "adresseLigne2",
            "baseName": "adresse_ligne_2",
            "type": "string"
        },
        {
            "name": "adresseLigne3",
            "baseName": "adresse_ligne_3",
            "type": "string"
        },
        {
            "name": "codePostal",
            "baseName": "code_postal",
            "type": "string"
        },
        {
            "name": "ville",
            "baseName": "ville",
            "type": "string"
        },
        {
            "name": "pays",
            "baseName": "pays",
            "type": "string"
        },
        {
            "name": "codePays",
            "baseName": "code_pays",
            "type": "string"
        },
        {
            "name": "pourcentageParts",
            "baseName": "pourcentage_parts",
            "type": "number"
        },
        {
            "name": "pourcentagePartsDirectes",
            "baseName": "pourcentage_parts_directes",
            "type": "number"
        },
        {
            "name": "pourcentagePartsIndirectes",
            "baseName": "pourcentage_parts_indirectes",
            "type": "number"
        },
        {
            "name": "pourcentagePartsVocationTitulaire",
            "baseName": "pourcentage_parts_vocation_titulaire",
            "type": "number"
        },
        {
            "name": "detailsPartsDirectes",
            "baseName": "details_parts_directes",
            "type": "EntrepriseFicheAllOfDetailsPartsDirectes"
        },
        {
            "name": "detailsPartsIndirectes",
            "baseName": "details_parts_indirectes",
            "type": "EntrepriseFicheAllOfDetailsPartsIndirectes"
        },
        {
            "name": "detailsPartsVocationTitulaire",
            "baseName": "details_parts_vocation_titulaire",
            "type": "EntrepriseFicheAllOfDetailsPartsVocationTitulaire"
        },
        {
            "name": "pourcentageVotes",
            "baseName": "pourcentage_votes",
            "type": "number"
        },
        {
            "name": "pourcentageVotesDirects",
            "baseName": "pourcentage_votes_directs",
            "type": "number"
        },
        {
            "name": "pourcentageVotesIndirect",
            "baseName": "pourcentage_votes_indirect",
            "type": "number"
        },
        {
            "name": "detailsVotesDirects",
            "baseName": "details_votes_directs",
            "type": "EntrepriseFicheAllOfDetailsVotesDirects"
        },
        {
            "name": "detailsVotesIndirects",
            "baseName": "details_votes_indirects",
            "type": "EntrepriseFicheAllOfDetailsVotesIndirects"
        },
        {
            "name": "detailsSocieteDeGestion",
            "baseName": "details_societe_de_gestion",
            "type": "EntrepriseFicheAllOfDetailsSocieteDeGestion"
        },
        {
            "name": "detentionPouvoirDecisionAg",
            "baseName": "detention_pouvoir_decision_ag",
            "type": "boolean"
        },
        {
            "name": "detentionPouvoirNomMembreConseilAdministration",
            "baseName": "detention_pouvoir_nom_membre_conseil_administration",
            "type": "boolean"
        },
        {
            "name": "detentionAutresMoyensControle",
            "baseName": "detention_autres_moyens_controle",
            "type": "boolean"
        },
        {
            "name": "beneficiaireRepresentantLegal",
            "baseName": "beneficiaire_representant_legal",
            "type": "boolean"
        },
        {
            "name": "representantLegalPlacementSansGestionDelegation",
            "baseName": "representant_legal_placement_sans_gestion_delegation",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EntrepriseFicheAllOfBeneficiairesEffectifs.attributeTypeMap;
    }
}

