/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Liste des statuts de l\'entreprise.
*/
export class EntrepriseFicheAllOfDerniersStatuts {
    /**
    * Date de dépôt des statuts, au format AAAA-MM-JJ.
    */
    'dateDepot'?: string;
    /**
    * Date de dépôt formaté des statuts, au format JJ/MM/AAAA.
    */
    'dateDepotFormate'?: string;
    /**
    * Disponibilité des statuts.
    */
    'disponible'?: boolean;
    /**
    * Nom du fichier pdf des statuts.
    */
    'nomFichierPdf'?: string;
    /**
    * Token des statuts.
    */
    'token'?: string;
    /**
    * Champ \"type\" du document contenant les statuts.
    */
    'type'?: string;
    /**
    * Champ \"decision\" du document contenant les statuts.
    */
    'decision'?: string;
    /**
    * Date de publication des statuts, au format AAAA-MM-JJ.
    */
    'dateActe'?: string;
    /**
    * Date de publication des statuts, au format JJ/MM/AAAA.
    */
    'dateActeFormate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateDepot",
            "baseName": "date_depot",
            "type": "string"
        },
        {
            "name": "dateDepotFormate",
            "baseName": "date_depot_formate",
            "type": "string"
        },
        {
            "name": "disponible",
            "baseName": "disponible",
            "type": "boolean"
        },
        {
            "name": "nomFichierPdf",
            "baseName": "nom_fichier_pdf",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "decision",
            "baseName": "decision",
            "type": "string"
        },
        {
            "name": "dateActe",
            "baseName": "date_acte",
            "type": "string"
        },
        {
            "name": "dateActeFormate",
            "baseName": "date_acte_formate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntrepriseFicheAllOfDerniersStatuts.attributeTypeMap;
    }
}

