/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Informations sur l\'immatriculation de l\'entreprise au Répertoire des Métiers.
*/
export class EntrepriseFicheAllOfRnm {
    /**
    * Date d\'immatriculation au Répertoire des Métiers, au format AAAA-MM-JJ.
    */
    'dateImmatriculation'?: string;
    /**
    * Date de radiation du Répertoire des Métiers, le cas échéant, au format AAAA-MM-JJ.
    */
    'dateRadiation'?: string;
    /**
    * Date de début d\'activé déclarée au Répertoire des Métiers, au format AAAA-MM-JJ.
    */
    'dateDebutActivite'?: string;
    /**
    * Date de cessation d\'activité déclarée au Répertoire des Métiers, le cas échéant, au format AAAA-MM-JJ.
    */
    'dateCessationActivite'?: string;
    /**
    * Chambre des métiers où l\'entreprise est immatriculée.
    */
    'chambreDesMetiers'?: string;
    /**
    * Qualification retenue par le Répertoire des Métiers.
    */
    'qualification'?: string;
    /**
    * Date de dernière mise à jour de l\'entreprise au Répertoire des Métiers, au format AAAA-MM-JJ.
    */
    'derniereMiseAJour'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateImmatriculation",
            "baseName": "date_immatriculation",
            "type": "string"
        },
        {
            "name": "dateRadiation",
            "baseName": "date_radiation",
            "type": "string"
        },
        {
            "name": "dateDebutActivite",
            "baseName": "date_debut_activite",
            "type": "string"
        },
        {
            "name": "dateCessationActivite",
            "baseName": "date_cessation_activite",
            "type": "string"
        },
        {
            "name": "chambreDesMetiers",
            "baseName": "chambre_des_metiers",
            "type": "string"
        },
        {
            "name": "qualification",
            "baseName": "qualification",
            "type": "string"
        },
        {
            "name": "derniereMiseAJour",
            "baseName": "derniere_mise_a_jour",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntrepriseFicheAllOfRnm.attributeTypeMap;
    }
}

