/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EntrepriseFicheAllOfActes {
    /**
    * Type de l\'acte.
    */
    'type'?: string;
    /**
    * Décision de l\'acte.
    */
    'decision'?: string;
    /**
    * Date de l\'acte, au format AAAA-MM-JJ.
    */
    'dateActe'?: string;
    /**
    * Date formatée de l\'acte, au format JJ/MM/AAAA.
    */
    'dateActeFormate'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "decision",
            "baseName": "decision",
            "type": "string"
        },
        {
            "name": "dateActe",
            "baseName": "date_acte",
            "type": "string"
        },
        {
            "name": "dateActeFormate",
            "baseName": "date_acte_formate",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return EntrepriseFicheAllOfActes.attributeTypeMap;
    }
}

