/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LienSuccession {
    /**
    * Numéro siret de l\'établissement au format xxxxxxxxxxxxxx.
    */
    'siret'?: string;
    /**
    * Date à laquelle la succession a eu lieu.
    */
    'date'?: string;
    /**
    * Vrai si le lien de succession concerne l\'établissement siège, faux sinon.
    */
    'transfertSiege'?: boolean;
    /**
    * Vrai s\'il y a [continuité économique](https://www.sirene.fr/sirene/public/variable/continuiteEconomique), faux sinon.
    */
    'continuiteEconomique'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "siret",
            "baseName": "siret",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "transfertSiege",
            "baseName": "transfert_siege",
            "type": "boolean"
        },
        {
            "name": "continuiteEconomique",
            "baseName": "continuite_economique",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return LienSuccession.attributeTypeMap;
    }
}

