/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Ratios {
    /**
    * Chiffre d\'affaires de l\'entreprise.
    */
    'chiffreAffaires'?: number;
    /**
    * Résultat de l\'entreprise.
    */
    'resultat'?: number;
    /**
    * Effectif de l\'entreprise.
    */
    'effectif'?: number;
    /**
    * Marge brute de l\'entreprise.
    */
    'margeBrute'?: number;
    /**
    * Excédent brut d\'exploitation (EBITDA) de l\'entreprise.
    */
    'excedentBrutExploitation'?: number;
    /**
    * Résultat d\'exploitation (EBIT) de l\'entreprise.
    */
    'resultatExploitation'?: number;
    /**
    * Taux de croissance du chiffre d\'affaires (en %) de l\'entreprise.
    */
    'tauxCroissanceChiffreAffaires'?: number;
    /**
    * Taux de marge brute (en %) de l\'entreprise.
    */
    'tauxMargeBrute'?: number;
    /**
    * Taux de marge d\'EBITDA (en %) de l\'entreprise.
    */
    'tauxMargeEBITDA'?: number;
    /**
    * Taux de marge opérationnelle (EBIT) (en %) de l\'entreprise.
    */
    'tauxMargeOperationnelle'?: number;
    /**
    * BFR (Besoin en fonds de roulement) de l\'entreprise.
    */
    'bFR'?: number;
    /**
    * BFR exploitation de l\'entreprise.
    */
    'bFRExploitation'?: number;
    /**
    * BFR hors exploitation de l\'entreprise.
    */
    'bFRHorsExploitation'?: number;
    /**
    * BFR (en jours de CA) de l\'entreprise.
    */
    'bFRJoursCA'?: number;
    /**
    * BFR exploitation (en jours de CA) de l\'entreprise.
    */
    'bFRExploitationJoursCA'?: number;
    /**
    * BFR hors exploitation (en jours de CA) de l\'entreprise.
    */
    'bFRHorsExploitationJoursCA'?: number;
    /**
    * Délai de paiement clients (en jours) de l\'entreprise.
    */
    'delaiPaiementClientsJours'?: number;
    /**
    * Délai de paiement fournisseurs (en jours) de l\'entreprise.
    */
    'delaiPaiementFournisseursJours'?: number;
    /**
    * Ratio des stocks / CA (en jours) de l\'entreprise.
    */
    'ratioStockCAJours'?: number;
    /**
    * Capacité d\'autofinancement de l\'entreprise.
    */
    'capaciteAutofinancement'?: number;
    /**
    * Capacité d\'autofinancement / CA (en %) de l\'entreprise.
    */
    'capaciteAutofinancementCA'?: number;
    /**
    * Fonds de roulement net global de l\'entreprise.
    */
    'fondsRoulementNetGlobal'?: number;
    /**
    * Couverture du BFR de l\'entreprise.
    */
    'couvertureBFR'?: number;
    /**
    * Trésorerie de l\'entreprise.
    */
    'tresorerie'?: number;
    /**
    * Dettes financières de l\'entreprise.
    */
    'dettesFinancieres'?: number;
    /**
    * Capacité de remboursement de l\'entreprise.
    */
    'capaciteRemboursement'?: number;
    /**
    * Ratio d\'endettement (Gearing) de l\'entreprise.
    */
    'ratioEndettement'?: number;
    /**
    * Autonomie financière (en %) de l\'entreprise.
    */
    'autonomieFinanciere'?: number;
    /**
    * Taux de levier (DFN/EBITDA) de l\'entreprise.
    */
    'tauxLevier'?: number;
    /**
    * Etat des dettes à 1 an au plus de l\'entreprise.
    */
    'etatDettes1AnAuPlus'?: number;
    /**
    * Liquidité générale de l\'entreprise.
    */
    'liquiditeGenerale'?: number;
    /**
    * Couverture des dettes de l\'entreprise.
    */
    'couvertureDettes'?: number;
    /**
    * Marge nette (en %) de l\'entreprise.
    */
    'margeNette'?: number;
    /**
    * Rentabilité sur fonds propres (en %) de l\'entreprise.
    */
    'rentabiliteFondsPropres'?: number;
    /**
    * Rentabilité économique (en %) de l\'entreprise.
    */
    'rentabiliteEconomique'?: number;
    /**
    * Valeur ajoutée de l\'entreprise.
    */
    'valeurAjoutee'?: number;
    /**
    * Valeur ajoutée / CA (en %) de l\'entreprise.
    */
    'valeurAjouteeCA'?: number;
    /**
    * Salaires et charges sociales de l\'entreprise.
    */
    'salairesChargesSociales'?: number;
    /**
    * Salaires / CA (en %) de l\'entreprise.
    */
    'salairesCA'?: number;
    /**
    * Impôts et taxes de l\'entreprise.
    */
    'impotsTaxes'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chiffreAffaires",
            "baseName": "chiffre_affaires",
            "type": "number"
        },
        {
            "name": "resultat",
            "baseName": "resultat",
            "type": "number"
        },
        {
            "name": "effectif",
            "baseName": "effectif",
            "type": "number"
        },
        {
            "name": "margeBrute",
            "baseName": "marge_brute",
            "type": "number"
        },
        {
            "name": "excedentBrutExploitation",
            "baseName": "excedent_brut_exploitation",
            "type": "number"
        },
        {
            "name": "resultatExploitation",
            "baseName": "resultat_exploitation",
            "type": "number"
        },
        {
            "name": "tauxCroissanceChiffreAffaires",
            "baseName": "taux_croissance_chiffre_affaires",
            "type": "number"
        },
        {
            "name": "tauxMargeBrute",
            "baseName": "taux_marge_brute",
            "type": "number"
        },
        {
            "name": "tauxMargeEBITDA",
            "baseName": "taux_marge_EBITDA",
            "type": "number"
        },
        {
            "name": "tauxMargeOperationnelle",
            "baseName": "taux_marge_operationnelle",
            "type": "number"
        },
        {
            "name": "bFR",
            "baseName": "BFR",
            "type": "number"
        },
        {
            "name": "bFRExploitation",
            "baseName": "BFR_exploitation",
            "type": "number"
        },
        {
            "name": "bFRHorsExploitation",
            "baseName": "BFR_hors_exploitation",
            "type": "number"
        },
        {
            "name": "bFRJoursCA",
            "baseName": "BFR_jours_CA",
            "type": "number"
        },
        {
            "name": "bFRExploitationJoursCA",
            "baseName": "BFR_exploitation_jours_CA",
            "type": "number"
        },
        {
            "name": "bFRHorsExploitationJoursCA",
            "baseName": "BFR_hors_exploitation_jours_CA",
            "type": "number"
        },
        {
            "name": "delaiPaiementClientsJours",
            "baseName": "delai_paiement_clients_jours",
            "type": "number"
        },
        {
            "name": "delaiPaiementFournisseursJours",
            "baseName": "delai_paiement_fournisseurs_jours",
            "type": "number"
        },
        {
            "name": "ratioStockCAJours",
            "baseName": "ratio_stock_CA_jours",
            "type": "number"
        },
        {
            "name": "capaciteAutofinancement",
            "baseName": "capacite_autofinancement",
            "type": "number"
        },
        {
            "name": "capaciteAutofinancementCA",
            "baseName": "capacite_autofinancement_CA",
            "type": "number"
        },
        {
            "name": "fondsRoulementNetGlobal",
            "baseName": "fonds_roulement_net_global",
            "type": "number"
        },
        {
            "name": "couvertureBFR",
            "baseName": "couverture_BFR",
            "type": "number"
        },
        {
            "name": "tresorerie",
            "baseName": "tresorerie",
            "type": "number"
        },
        {
            "name": "dettesFinancieres",
            "baseName": "dettes_financieres",
            "type": "number"
        },
        {
            "name": "capaciteRemboursement",
            "baseName": "capacite_remboursement",
            "type": "number"
        },
        {
            "name": "ratioEndettement",
            "baseName": "ratio_endettement",
            "type": "number"
        },
        {
            "name": "autonomieFinanciere",
            "baseName": "autonomie_financiere",
            "type": "number"
        },
        {
            "name": "tauxLevier",
            "baseName": "taux_levier",
            "type": "number"
        },
        {
            "name": "etatDettes1AnAuPlus",
            "baseName": "etat_dettes_1_an_au_plus",
            "type": "number"
        },
        {
            "name": "liquiditeGenerale",
            "baseName": "liquidite_generale",
            "type": "number"
        },
        {
            "name": "couvertureDettes",
            "baseName": "couverture_dettes",
            "type": "number"
        },
        {
            "name": "margeNette",
            "baseName": "marge_nette",
            "type": "number"
        },
        {
            "name": "rentabiliteFondsPropres",
            "baseName": "rentabilite_fonds_propres",
            "type": "number"
        },
        {
            "name": "rentabiliteEconomique",
            "baseName": "rentabilite_economique",
            "type": "number"
        },
        {
            "name": "valeurAjoutee",
            "baseName": "valeur_ajoutee",
            "type": "number"
        },
        {
            "name": "valeurAjouteeCA",
            "baseName": "valeur_ajoutee_CA",
            "type": "number"
        },
        {
            "name": "salairesChargesSociales",
            "baseName": "salaires_charges_sociales",
            "type": "number"
        },
        {
            "name": "salairesCA",
            "baseName": "salaires_CA",
            "type": "number"
        },
        {
            "name": "impotsTaxes",
            "baseName": "impots_taxes",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return Ratios.attributeTypeMap;
    }
}

