/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Recherche200ResponseResultatsInner } from './recherche200ResponseResultatsInner';

export class Recherche200Response {
    /**
    * Liste des entreprises qui correspondent à la recherche.
    */
    'resultats'?: Array<Recherche200ResponseResultatsInner>;
    /**
    * Nombre d\'entreprises qui correspondent à la recherche.
    */
    'total'?: number;
    /**
    * Page actuelle.
    */
    'page'?: number;
    /**
    * Présent uniquement en cas d\'utilisation du paramètre `curseur`. Contient le curseur courant à envoyer en paramètre `curseur` de la requête suivantes.
    */
    'curseurSuivant'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resultats",
            "baseName": "resultats",
            "type": "Array<Recherche200ResponseResultatsInner>"
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number"
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number"
        },
        {
            "name": "curseurSuivant",
            "baseName": "curseurSuivant",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return Recherche200Response.attributeTypeMap;
    }
}

