/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EntrepriseRecherche } from './entrepriseRecherche';

export class RechercheBeneficiaires200ResponseResultatsInner {
    /**
    * Nom du bénéficiaire effectif.
    */
    'nom'?: string;
    /**
    * Nom d\'usage du bénéficiaire effectif.
    */
    'nomUsage'?: string;
    /**
    * Prénom du bénéficiaire effectif.
    */
    'prenom'?: string;
    /**
    * Pseudonyme du bénéficiaire effectif.
    */
    'pseudonyme'?: string;
    /**
    * Nom complet du bénéficiaire effectif.
    */
    'nomComplet'?: string;
    /**
    * Mois et année de naissance du bénéficiaire effectif, au format MM/AAAA.
    */
    'dateDeNaissanceFormate'?: string;
    /**
    * Nationalité du bénéficiaire effectif.
    */
    'nationalite'?: string;
    /**
    * Parts détenues par le bénéficiaire effectif, en pourcentage des parts totales.
    */
    'pourcentageParts'?: number;
    /**
    * Droits de vote détenus par le bénéficiaire effectif, en pourcentage des droits de vote totaux.
    */
    'pourcentageVotes'?: number;
    /**
    * Droits de vote détenus de façon indirecte par le bénéficiaire effectif, en pourcentage des droits de vote totaux.
    */
    'pourcentageVotesIndirect'?: number;
    /**
    * Droits de vote détenus de façon directe par le bénéficiaire effectif, en pourcentage des droits de vote totaux.
    */
    'pourcentageVotesDirects'?: number;
    /**
    * Vaut vrai s\'il existe d\'autres moyens de contrôle.
    */
    'detentionAutresMoyensControle'?: boolean;
    /**
    * Vaut vrai dans le cas où le bénéficiaire effectif a été défini comme le représentant légal par défaut.
    */
    'beneficiaireRepresentantLegal'?: boolean;
    /**
    * Première ligne de l\'adresse du bénéficiaire effectif.
    */
    'adresseLigne1'?: string;
    /**
    * Deuxième ligne de l\'adresse du bénéficiaire effectif.
    */
    'adresseLigne2'?: string;
    /**
    * Troisième ligne de l\'adresse du bénéficiaire effectif.
    */
    'adresseLigne3'?: string;
    /**
    * Parts dont le bénéficiaire effectif a vocation à devenir titulaire par l\'effet d\'un acte juridique, en pourcentage des parts totales.
    */
    'pourcentagePartsVocationTitulaire'?: number;
    /**
    * Vaut vrai dans le cas où le bénéficiaire effectif est le représentant légal du placement collectif (cas où le placement collectif n\'a pas délégué sa gestion à une société de gestion).
    */
    'representantLegalPlacementSansGestionDelegation'?: boolean;
    /**
    * Code postal du bénéficiaire effectif.
    */
    'codePostal'?: string;
    /**
    * Vaut vrai si le moyen de contrôle est le pouvoir de nommer ou de révoquer la majorité des membres des organes d\'administration, de gestion, de direction ou de surveillance de la personne morale.
    */
    'detentionPouvoirNomMembreConseilAdministration'?: boolean;
    /**
    * Ville du bénéficiaire effectif.
    */
    'ville'?: string;
    /**
    * Date de naissance complète du bénéficiaire effectif, au format JJ/MM/AAAA.
    */
    'dateDeNaissanceCompleteFormatee'?: string;
    /**
    * Parts détenues de façon directe par le bénéficiaire effectif, en pourcentage des parts totales.
    */
    'pourcentagePartsDirectes'?: number;
    /**
    * Parts détenues de façon indirecte par le bénéficiaire effectif, en pourcentage des parts totales.
    */
    'pourcentagePartsIndirectes'?: number;
    /**
    * Pays de naissance du bénéficiaire effectif.
    */
    'paysDeNaissance'?: string;
    /**
    * Code du pays de naissance du bénéficiaire effectif.
    */
    'codePaysDeNaissance'?: string;
    /**
    * Ville de naissance du bénéficiaire effectif.
    */
    'villeDeNaissance'?: string;
    /**
    * Vaut vrai pour les moyens de contrôle sur les organes d\'administration, de gestion, de direction ou de surveillance de la personne morale autre que le pouvoir de nommer ou de révoquer la majorité des membres.
    */
    'detentionPouvoirDecisionAg'?: boolean;
    /**
    * Pays du bénéficiaire effectif.
    */
    'pays'?: string;
    /**
    * Mois et année de naissance du bénéficiaire effectif, au format MM/AAAA.
    */
    'dateDeNaissanceFormatee'?: string;
    /**
    * Code pays du bénéficiaire effectif.
    */
    'codePays'?: string;
    /**
    * Liste des entreprises dont le bénéficiaire effectif est bénéficiaire effectif, dans la limite de 100 entreprises.
    */
    'entreprises'?: Array<EntrepriseRecherche>;
    /**
    * Nombre d\'entreprises du bénéficiaire effectif au total.
    */
    'nbEntreprisesTotal'?: number;
    /**
    * Liste des entreprises dont le bénéficiaire effectif est dirigeant (sans forcément en être bénéficiaire effectif), dans la limite de 100 entreprises.
    */
    'entreprisesDirigeant'?: Array<EntrepriseRecherche>;
    /**
    * Nombre d\'entreprises dont le bénéficiaire effectif est dirigeant au total.
    */
    'nbEntreprisesDirigeantTotal'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nom",
            "baseName": "nom",
            "type": "string"
        },
        {
            "name": "nomUsage",
            "baseName": "nom_usage",
            "type": "string"
        },
        {
            "name": "prenom",
            "baseName": "prenom",
            "type": "string"
        },
        {
            "name": "pseudonyme",
            "baseName": "pseudonyme",
            "type": "string"
        },
        {
            "name": "nomComplet",
            "baseName": "nom_complet",
            "type": "string"
        },
        {
            "name": "dateDeNaissanceFormate",
            "baseName": "date_de_naissance_formate",
            "type": "string"
        },
        {
            "name": "nationalite",
            "baseName": "nationalite",
            "type": "string"
        },
        {
            "name": "pourcentageParts",
            "baseName": "pourcentage_parts",
            "type": "number"
        },
        {
            "name": "pourcentageVotes",
            "baseName": "pourcentage_votes",
            "type": "number"
        },
        {
            "name": "pourcentageVotesIndirect",
            "baseName": "pourcentage_votes_indirect",
            "type": "number"
        },
        {
            "name": "pourcentageVotesDirects",
            "baseName": "pourcentage_votes_directs",
            "type": "number"
        },
        {
            "name": "detentionAutresMoyensControle",
            "baseName": "detention_autres_moyens_controle",
            "type": "boolean"
        },
        {
            "name": "beneficiaireRepresentantLegal",
            "baseName": "beneficiaire_representant_legal",
            "type": "boolean"
        },
        {
            "name": "adresseLigne1",
            "baseName": "adresse_ligne_1",
            "type": "string"
        },
        {
            "name": "adresseLigne2",
            "baseName": "adresse_ligne_2",
            "type": "string"
        },
        {
            "name": "adresseLigne3",
            "baseName": "adresse_ligne_3",
            "type": "string"
        },
        {
            "name": "pourcentagePartsVocationTitulaire",
            "baseName": "pourcentage_parts_vocation_titulaire",
            "type": "number"
        },
        {
            "name": "representantLegalPlacementSansGestionDelegation",
            "baseName": "representant_legal_placement_sans_gestion_delegation",
            "type": "boolean"
        },
        {
            "name": "codePostal",
            "baseName": "code_postal",
            "type": "string"
        },
        {
            "name": "detentionPouvoirNomMembreConseilAdministration",
            "baseName": "detention_pouvoir_nom_membre_conseil_administration",
            "type": "boolean"
        },
        {
            "name": "ville",
            "baseName": "ville",
            "type": "string"
        },
        {
            "name": "dateDeNaissanceCompleteFormatee",
            "baseName": "date_de_naissance_complete_formatee",
            "type": "string"
        },
        {
            "name": "pourcentagePartsDirectes",
            "baseName": "pourcentage_parts_directes",
            "type": "number"
        },
        {
            "name": "pourcentagePartsIndirectes",
            "baseName": "pourcentage_parts_indirectes",
            "type": "number"
        },
        {
            "name": "paysDeNaissance",
            "baseName": "pays_de_naissance",
            "type": "string"
        },
        {
            "name": "codePaysDeNaissance",
            "baseName": "code_pays_de_naissance",
            "type": "string"
        },
        {
            "name": "villeDeNaissance",
            "baseName": "ville_de_naissance",
            "type": "string"
        },
        {
            "name": "detentionPouvoirDecisionAg",
            "baseName": "detention_pouvoir_decision_ag",
            "type": "boolean"
        },
        {
            "name": "pays",
            "baseName": "pays",
            "type": "string"
        },
        {
            "name": "dateDeNaissanceFormatee",
            "baseName": "date_de_naissance_formatee",
            "type": "string"
        },
        {
            "name": "codePays",
            "baseName": "code_pays",
            "type": "string"
        },
        {
            "name": "entreprises",
            "baseName": "entreprises",
            "type": "Array<EntrepriseRecherche>"
        },
        {
            "name": "nbEntreprisesTotal",
            "baseName": "nb_entreprises_total",
            "type": "number"
        },
        {
            "name": "entreprisesDirigeant",
            "baseName": "entreprises_dirigeant",
            "type": "Array<EntrepriseRecherche>"
        },
        {
            "name": "nbEntreprisesDirigeantTotal",
            "baseName": "nb_entreprises_dirigeant_total",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return RechercheBeneficiaires200ResponseResultatsInner.attributeTypeMap;
    }
}

