/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RepresentantRecherche {
    /**
    * Qualité du représentant.
    */
    'qualite'?: string;
    /**
    * Vrai si le représentant est une personne morale, faux si personne physique.
    */
    'personneMorale'?: boolean;
    /**
    * Date de prise de poste du représentant.
    */
    'datePriseDePoste'?: string;
    /**
    * Sexe supposé du dirigeant si personne physique. F pour féminin, M pour masculin. Ce champ est estimé à partir du prénom du dirigeant.
    */
    'sexe'?: string;
    /**
    * Nom du représentant.
    */
    'nom'?: string;
    /**
    * Prénoms du représentant.
    */
    'prenom'?: string;
    /**
    * Prénom usuel du représentant.
    */
    'prenomUsuel'?: string;
    /**
    * Nom complet du représentant.
    */
    'nomComplet'?: string;
    /**
    * Date de naissance du représentant.
    */
    'dateDeNaissance'?: string;
    /**
    * Date de naissance formatée du représentant.
    */
    'dateDeNaissanceFormate'?: string;
    /**
    * Age du représentant.
    */
    'age'?: number;
    /**
    * Nationalité du représentant.
    */
    'nationalite'?: string;
    /**
    * Code nationalité du représentant
    */
    'codeNationalite'?: string;
    /**
    * Ville de naissance du représentant.
    */
    'villeDeNaissance'?: string;
    /**
    * Pays de naissance du représentant.
    */
    'paysDeNaissance'?: string;
    /**
    * Code du pays de naissance du représentant.
    */
    'codePaysDeNaissance'?: string;
    /**
    * Première ligne de l\'adresse du représentant.
    */
    'adresseLigne1'?: string;
    /**
    * Deuxième ligne de l\'adresse du représentant.
    */
    'adresseLigne2'?: string;
    /**
    * Troisième ligne de l\'adresse du représentant.
    */
    'adresseLigne3'?: string;
    /**
    * Code postal du représentant.
    */
    'codePostal'?: string;
    /**
    * Ville du représentant.
    */
    'ville'?: string;
    /**
    * Pays du représentant.
    */
    'pays'?: string;
    /**
    * Code du pays du représentant
    */
    'codePays'?: string;
    /**
    * Vaut vrai si le représentant est toujours à son poste.
    */
    'actuel'?: boolean;
    /**
    * Date de départ de poste dans le cas où le représentant n\'est plus un représentant actuel, au format AAAA-MM-JJ.
    */
    'dateDepartDePoste'?: string;
    /**
    * Forme juridique du représentant dans le cas d\'une personne morale.
    */
    'formeJuridique'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "qualite",
            "baseName": "qualite",
            "type": "string"
        },
        {
            "name": "personneMorale",
            "baseName": "personne_morale",
            "type": "boolean"
        },
        {
            "name": "datePriseDePoste",
            "baseName": "date_prise_de_poste",
            "type": "string"
        },
        {
            "name": "sexe",
            "baseName": "sexe",
            "type": "string"
        },
        {
            "name": "nom",
            "baseName": "nom",
            "type": "string"
        },
        {
            "name": "prenom",
            "baseName": "prenom",
            "type": "string"
        },
        {
            "name": "prenomUsuel",
            "baseName": "prenom_usuel",
            "type": "string"
        },
        {
            "name": "nomComplet",
            "baseName": "nom_complet",
            "type": "string"
        },
        {
            "name": "dateDeNaissance",
            "baseName": "date_de_naissance",
            "type": "string"
        },
        {
            "name": "dateDeNaissanceFormate",
            "baseName": "date_de_naissance_formate",
            "type": "string"
        },
        {
            "name": "age",
            "baseName": "age",
            "type": "number"
        },
        {
            "name": "nationalite",
            "baseName": "nationalite",
            "type": "string"
        },
        {
            "name": "codeNationalite",
            "baseName": "code_nationalite",
            "type": "string"
        },
        {
            "name": "villeDeNaissance",
            "baseName": "ville_de_naissance",
            "type": "string"
        },
        {
            "name": "paysDeNaissance",
            "baseName": "pays_de_naissance",
            "type": "string"
        },
        {
            "name": "codePaysDeNaissance",
            "baseName": "code_pays_de_naissance",
            "type": "string"
        },
        {
            "name": "adresseLigne1",
            "baseName": "adresse_ligne_1",
            "type": "string"
        },
        {
            "name": "adresseLigne2",
            "baseName": "adresse_ligne_2",
            "type": "string"
        },
        {
            "name": "adresseLigne3",
            "baseName": "adresse_ligne_3",
            "type": "string"
        },
        {
            "name": "codePostal",
            "baseName": "code_postal",
            "type": "string"
        },
        {
            "name": "ville",
            "baseName": "ville",
            "type": "string"
        },
        {
            "name": "pays",
            "baseName": "pays",
            "type": "string"
        },
        {
            "name": "codePays",
            "baseName": "code_pays",
            "type": "string"
        },
        {
            "name": "actuel",
            "baseName": "actuel",
            "type": "boolean"
        },
        {
            "name": "dateDepartDePoste",
            "baseName": "date_depart_de_poste",
            "type": "string"
        },
        {
            "name": "formeJuridique",
            "baseName": "forme_juridique",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RepresentantRecherche.attributeTypeMap;
    }
}

