/**
 * Pappers API
 * L\'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d\'API dans les requêtes, en utilisant le paramètre `api_token`.  L\'URL d\'accès à l\'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L\'historique des modifications (changelog) est accessible à l\'url suivante : https://www.pappers.fr/api/changelog 
 *
 * The version of the OpenAPI document: 2.7.0
 * Contact: support@pappers.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Suggestions200ResponseResultatsDenominationInner } from './suggestions200ResponseResultatsDenominationInner';
import { Suggestions200ResponseResultatsNomCompletInner } from './suggestions200ResponseResultatsNomCompletInner';
import { Suggestions200ResponseResultatsNomEntrepriseInner } from './suggestions200ResponseResultatsNomEntrepriseInner';
import { Suggestions200ResponseResultatsRepresentantInner } from './suggestions200ResponseResultatsRepresentantInner';
import { Suggestions200ResponseResultatsSirenInner } from './suggestions200ResponseResultatsSirenInner';
import { Suggestions200ResponseResultatsSiretInner } from './suggestions200ResponseResultatsSiretInner';

export class Suggestions200Response {
    /**
    * Liste des entreprises dont le nom (dénomination ou nom/prénom) peut compléter la recherche textuelle. Uniquement présent si le paramètre `cibles` contient `nom_entreprise`.
    */
    'resultatsNomEntreprise'?: Array<Suggestions200ResponseResultatsNomEntrepriseInner>;
    /**
    * Liste des entreprises dont la dénomination peut compléter la recherche textuelle (concerne les personnes morales seulement). Uniquement présent si le paramètre `cibles` contient `denomination`.
    */
    'resultatsDenomination'?: Array<Suggestions200ResponseResultatsDenominationInner>;
    /**
    * Liste des entreprises dont le nom complet (nom + prénom ou prénom + nom) peut compléter la recherche textuelle (concerne les personnes physiques seulement). Uniquement présent si le paramètre `cibles` contient `nom_complet`.
    */
    'resultatsNomComplet'?: Array<Suggestions200ResponseResultatsNomCompletInner>;
    /**
    * Liste des représentants dont le nom complet (nom + prénom ou prénom + nom) peut compléter la recherche textuelle. Uniquement présent si le paramètre `cibles` contient `representant`.
    */
    'resultatsRepresentant'?: Array<Suggestions200ResponseResultatsRepresentantInner>;
    /**
    * Liste des entreprises dont le numéro SIREN peut compléter la recherche textuelle. Uniquement présent si le paramètre `cibles` contient `siren`.
    */
    'resultatsSiren'?: Array<Suggestions200ResponseResultatsSirenInner>;
    /**
    * Liste des entreprises dont le numéro SIRET peut compléter la recherche textuelle. Uniquement présent si le paramètre `cibles` contient `siret`.
    */
    'resultatsSiret'?: Array<Suggestions200ResponseResultatsSiretInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "resultatsNomEntreprise",
            "baseName": "resultats_nom_entreprise",
            "type": "Array<Suggestions200ResponseResultatsNomEntrepriseInner>"
        },
        {
            "name": "resultatsDenomination",
            "baseName": "resultats_denomination",
            "type": "Array<Suggestions200ResponseResultatsDenominationInner>"
        },
        {
            "name": "resultatsNomComplet",
            "baseName": "resultats_nom_complet",
            "type": "Array<Suggestions200ResponseResultatsNomCompletInner>"
        },
        {
            "name": "resultatsRepresentant",
            "baseName": "resultats_representant",
            "type": "Array<Suggestions200ResponseResultatsRepresentantInner>"
        },
        {
            "name": "resultatsSiren",
            "baseName": "resultats_siren",
            "type": "Array<Suggestions200ResponseResultatsSirenInner>"
        },
        {
            "name": "resultatsSiret",
            "baseName": "resultats_siret",
            "type": "Array<Suggestions200ResponseResultatsSiretInner>"
        }    ];

    static getAttributeTypeMap() {
        return Suggestions200Response.attributeTypeMap;
    }
}

