=begin
#Pappers API

#L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 

The version of the OpenAPI document: 2.7.0
Contact: support@pappers.fr
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/association'
require 'openapi_client/models/association_adresse_gestionnaire'
require 'openapi_client/models/association_adresse_siege'
require 'openapi_client/models/association_publications_joafe'
require 'openapi_client/models/beneficiaire'
require 'openapi_client/models/bodacc'
require 'openapi_client/models/bodacc_achat_all_of'
require 'openapi_client/models/bodacc_creation_all_of'
require 'openapi_client/models/bodacc_depot_des_comptes_all_of'
require 'openapi_client/models/bodacc_immatriculation_all_of'
require 'openapi_client/models/bodacc_modification_all_of'
require 'openapi_client/models/bodacc_procedure_collective_all_of'
require 'openapi_client/models/bodacc_vente_all_of'
require 'openapi_client/models/comptes_annuels200_response_value_inner'
require 'openapi_client/models/comptes_annuels200_response_value_inner_sections_inner'
require 'openapi_client/models/comptes_annuels200_response_value_inner_sections_inner_liasses_inner'
require 'openapi_client/models/comptes_annuels200_response_value_inner_sections_inner_liasses_inner_colonnes_inner'
require 'openapi_client/models/document'
require 'openapi_client/models/document_acte_all_of'
require 'openapi_client/models/document_acte_all_of_titres'
require 'openapi_client/models/document_comptes_all_of'
require 'openapi_client/models/entreprise_base'
require 'openapi_client/models/entreprise_base_conventions_collectives_inner'
require 'openapi_client/models/entreprise_fiche'
require 'openapi_client/models/entreprise_fiche_all_of'
require 'openapi_client/models/entreprise_fiche_all_of_actes'
require 'openapi_client/models/entreprise_fiche_all_of_beneficiaires_effectifs'
require 'openapi_client/models/entreprise_fiche_all_of_classes'
require 'openapi_client/models/entreprise_fiche_all_of_comptes'
require 'openapi_client/models/entreprise_fiche_all_of_depots_actes'
require 'openapi_client/models/entreprise_fiche_all_of_derniers_statuts'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_directes'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_indirectes'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_indirectes_details_en_indivision'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_indirectes_details_en_personne_morale'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_vocation_titulaire'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_vocation_titulaire_details_directes'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_vocation_titulaire_details_indirectes'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_vocation_titulaire_details_indirectes_details_en_indivision'
require 'openapi_client/models/entreprise_fiche_all_of_details_parts_vocation_titulaire_details_indirectes_details_en_personne_morale'
require 'openapi_client/models/entreprise_fiche_all_of_details_societe_de_gestion'
require 'openapi_client/models/entreprise_fiche_all_of_details_votes_directs'
require 'openapi_client/models/entreprise_fiche_all_of_details_votes_indirects'
require 'openapi_client/models/entreprise_fiche_all_of_details_votes_indirects_details_en_indivision'
require 'openapi_client/models/entreprise_fiche_all_of_details_votes_indirects_details_en_personne_morale'
require 'openapi_client/models/entreprise_fiche_all_of_evenements'
require 'openapi_client/models/entreprise_fiche_all_of_extrait_immatriculation'
require 'openapi_client/models/entreprise_fiche_all_of_marques'
require 'openapi_client/models/entreprise_fiche_all_of_procedures_collectives'
require 'openapi_client/models/entreprise_fiche_all_of_rnm'
require 'openapi_client/models/entreprise_recherche'
require 'openapi_client/models/entreprise_recherche_all_of'
require 'openapi_client/models/etablissement_fiche'
require 'openapi_client/models/etablissement_fiche_domiciliation'
require 'openapi_client/models/etablissement_recherche'
require 'openapi_client/models/lien_succession'
require 'openapi_client/models/personne_marque'
require 'openapi_client/models/publication'
require 'openapi_client/models/ratios'
require 'openapi_client/models/recherche200_response'
require 'openapi_client/models/recherche200_response_resultats_inner'
require 'openapi_client/models/recherche200_response_resultats_inner_all_of'
require 'openapi_client/models/recherche200_response_resultats_inner_all_of_publications_inner'
require 'openapi_client/models/recherche200_response_resultats_inner_all_of_publications_inner_all_of'
require 'openapi_client/models/recherche_beneficiaires200_response'
require 'openapi_client/models/recherche_beneficiaires200_response_resultats_inner'
require 'openapi_client/models/recherche_beneficiaires200_response_resultats_inner_all_of'
require 'openapi_client/models/recherche_dirigeants200_response'
require 'openapi_client/models/recherche_dirigeants200_response_resultats_inner'
require 'openapi_client/models/recherche_dirigeants200_response_resultats_inner_all_of'
require 'openapi_client/models/recherche_documents200_response'
require 'openapi_client/models/recherche_documents200_response_resultats_inner_all_of'
require 'openapi_client/models/recherche_publications200_response'
require 'openapi_client/models/recherche_publications200_response_resultats_inner'
require 'openapi_client/models/representant'
require 'openapi_client/models/representant_recherche'
require 'openapi_client/models/representant_recherche_all_of'
require 'openapi_client/models/suggestions200_response'
require 'openapi_client/models/suggestions200_response_resultats_denomination_inner'
require 'openapi_client/models/suggestions200_response_resultats_denomination_inner_all_of'
require 'openapi_client/models/suggestions200_response_resultats_nom_complet_inner'
require 'openapi_client/models/suggestions200_response_resultats_nom_complet_inner_all_of'
require 'openapi_client/models/suggestions200_response_resultats_nom_entreprise_inner'
require 'openapi_client/models/suggestions200_response_resultats_nom_entreprise_inner_all_of'
require 'openapi_client/models/suggestions200_response_resultats_representant_inner'
require 'openapi_client/models/suggestions200_response_resultats_representant_inner_all_of'
require 'openapi_client/models/suggestions200_response_resultats_siren_inner'
require 'openapi_client/models/suggestions200_response_resultats_siren_inner_all_of'
require 'openapi_client/models/suggestions200_response_resultats_siret_inner'
require 'openapi_client/models/suggestions200_response_resultats_siret_inner_all_of'
require 'openapi_client/models/suivi_jetons200_response'
require 'openapi_client/models/surveillance_dirigeant200_response'
require 'openapi_client/models/surveillance_dirigeant201_response'
require 'openapi_client/models/surveillance_dirigeant_request_inner'
require 'openapi_client/models/surveillance_entreprise200_response'
require 'openapi_client/models/surveillance_entreprise201_response'
require 'openapi_client/models/surveillance_entreprise_request_inner'
require 'openapi_client/models/surveillance_liste_informations_request'
require 'openapi_client/models/surveillance_notifications_delete200_response'
require 'openapi_client/models/bodacc_achat'
require 'openapi_client/models/bodacc_creation'
require 'openapi_client/models/bodacc_depot_des_comptes'
require 'openapi_client/models/bodacc_immatriculation'
require 'openapi_client/models/bodacc_modification'
require 'openapi_client/models/bodacc_procedure_collective'
require 'openapi_client/models/bodacc_radiation'
require 'openapi_client/models/bodacc_vente'
require 'openapi_client/models/document_acte'
require 'openapi_client/models/document_comptes'
require 'openapi_client/models/recherche_documents200_response_resultats_inner'

# APIs
require 'openapi_client/api/comptes_annuels_api'
require 'openapi_client/api/documents_api'
require 'openapi_client/api/fiche_association_api'
require 'openapi_client/api/fiche_entreprise_api'
require 'openapi_client/api/recherche_api'
require 'openapi_client/api/suggestions_autocomplete_api'
require 'openapi_client/api/suivi_utilisation_api'
require 'openapi_client/api/surveillance_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
