=begin
#Pappers API

#L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 

The version of the OpenAPI document: 2.7.0
Contact: support@pappers.fr
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DocumentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DocumentsApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DocumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentsApi' do
    it 'should create an instance of DocumentsApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DocumentsApi)
    end
  end

  # unit tests for document_avis_situation_insee
  # Télécharge l&#39;avis de situation INSEE d&#39;une entreprise à partir de son SIREN ou SIRET.
  # Vous devez fournir soit le SIREN, soit le SIRET. Le document vous sera envoyé au format PDF.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [String] :siren SIREN de l&#39;entreprise
  # @option opts [String] :siret SIRET de l&#39;entreprise
  # @return [File]
  describe 'document_avis_situation_insee test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for document_beneficiaires_effectifs
  # Télécharge la déclaration des bénéficiaires effectifs d&#39;une entreprise à partir de son SIREN.
  # Vous devez fournir le SIREN. Le document vous sera envoyé au format PDF.  Seules les autorités de contrôle (&lt;a rel&#x3D;&#39;noreferrer noopener&#39; target&#x3D;&#39;_blank&#39; href&#x3D;&#39;https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041578272/&#39;&gt;article R. 561-57 du Code monétaire et financier en dénombre 18&lt;/a&gt;) et les personnes assujetties à la lutte contre le blanchiment des capitaux et le financement du terrorisme (&lt;a rel&#x3D;&#39;noreferrer noopener&#39; target&#x3D;&#39;_blank&#39; href&#x3D;&#39;https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000042648575/&#39;&gt;article L. 561-2 du code monétaire et financier&lt;/a&gt;) peuvent accéder à ces informations.  Pour pouvoir utiliser cette route veuillez nous contacter au préalable à api@pappers.fr
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [String] :siren SIREN de l&#39;entreprise
  # @return [File]
  describe 'document_beneficiaires_effectifs test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for document_extrait_inpi
  # Télécharge l&#39;extrait INPI d&#39;une entreprise à partir de son SIREN ou SIRET.
  # Vous devez fournir soit le SIREN, soit le SIRET. Le document vous sera envoyé au format PDF.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [String] :siren SIREN de l&#39;entreprise
  # @option opts [String] :siret SIRET de l&#39;entreprise
  # @return [File]
  describe 'document_extrait_inpi test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for document_extrait_pappers
  # Télécharge l&#39;extrait Pappers d&#39;une entreprise à partir de son SIREN ou SIRET.
  # Vous devez fournir soit le SIREN, soit le SIRET. Le document vous sera envoyé au format PDF.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [String] :siren SIREN de l&#39;entreprise
  # @option opts [String] :siret SIRET de l&#39;entreprise
  # @return [File]
  describe 'document_extrait_pappers test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for document_status
  # Télécharge les derniers statuts disponibles d&#39;une entreprise à partir de son SIREN ou SIRET.
  # Vous devez fournir soit le SIREN, soit le SIRET. Le document vous sera envoyé au format PDF.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [String] :siren SIREN de l&#39;entreprise
  # @option opts [String] :siret SIRET de l&#39;entreprise
  # @return [File]
  describe 'document_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for document_telechargement
  # Télécharge un document PDF ou XLSX à partir de son token.
  # Vous devez fournir le token du document. Le document vous sera envoyé au format PDF ou XLSX.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param token Token du document
  # @param [Hash] opts the optional parameters
  # @return [File]
  describe 'document_telechargement test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
