=begin
#Pappers API

#L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 

The version of the OpenAPI document: 2.7.0
Contact: support@pappers.fr
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::FicheAssociationApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FicheAssociationApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::FicheAssociationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FicheAssociationApi' do
    it 'should create an instance of FicheAssociationApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::FicheAssociationApi)
    end
  end

  # unit tests for association
  # Récupère l&#39;ensemble des informations disponibles sur une association.
  # Vous devez fournir soit l&#39;identifiant de l&#39;association, soit le SIREN, soit le SIRET.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id_association Identifiant de l&#39;association
  # @option opts [String] :siret SIRET de l&#39;association
  # @option opts [String] :siren SIREN de l&#39;association
  # @return [Association]
  describe 'association test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
