=begin
#Pappers API

#L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 

The version of the OpenAPI document: 2.7.0
Contact: support@pappers.fr
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::RechercheApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RechercheApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::RechercheApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RechercheApi' do
    it 'should create an instance of RechercheApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::RechercheApi)
    end
  end

  # unit tests for recherche
  # Recherche les entreprises qui correspondent à des critères.
  # Tous les paramètres sont optionnels et servent à filtrer la recherche. Les différentes entreprises seront renvoyées dans un tableau &#x60;resultats&#x60;, et le nombre total de résultats sera renvoyé dans le champ &#x60;total&#x60;.  Pour parcourir l&#39;ensemble des résultats, deux solutions sont possibles :  - La pagination (paramètres &#x60;page&#x60; et &#x60;par_page&#x60;), limitée aux 400 premiers résultats ; - Les curseurs (paramètres &#x60;curseur&#x60; et &#x60;par_curseur&#x60;).  Cette route permet également le téléchargement d&#39;un export des résultats de recherche au format xlsx, csv ou json. Il faut pour cela utiliser le paramètre &#x60;export&#x60;. 
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page de résultats. Valeur par défaut : &#x60;1&#x60;.
  # @option opts [Integer] :par_page Nombre de résultats affichés sur une page. Valeur par défaut : &#x60;10&#x60;.
  # @option opts [String] :curseur Curseur servant à parcourir l&#39;ensemble des résultats (alternativement à la pagination qui est limitée à 400 résultats maximum). Doit valoir &#x60;*&#x60; pour la première requête, et doit pour les requêtes suivantes reprendre la valeur &#x60;curseurSuivant&#x60; retournée par la dernière réponse.
  # @option opts [Integer] :par_curseur Nombre de résultats affichés par curseur. Valeur par défaut : &#x60;50&#x60;. Valeur minimale: &#x60;1&#x60;. Valeur maximale : &#x60;1000&#x60;.
  # @option opts [String] :bases Bases de données dans lesquelles rechercher. Il est possible d&#39;indiquer plusieurs bases en les séparant par des virgules. Valeur par défaut : &#x60;\&quot;entreprises\&quot;&#x60;.
  # @option opts [String] :precision Niveau de précision de la recherche. Valeur par défaut : &#x60;\&quot;standard\&quot;&#x60;.
  # @option opts [String] :export Si ce champ est renseigné, la requête renverra directement un export de l&#39;ensemble des résultats de la recherche.
  # @option opts [String] :q Texte à rechercher. Dénomination pour une personne morale, nom et prénom pour une personne physique. Si vous recherchez dans plusieurs bases, ce paramètre sera utilisé pour rechercher dans toutes les bases.
  # @option opts [String] :siege Défini si la requête se base sur le siège
  # @option opts [String] :code_naf Code NAF de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes NAF en les séparant par des virgules.
  # @option opts [String] :departement Numéro de département de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs départements en les séparant par des virgules.
  # @option opts [String] :region Code de la région de l&#39;un des établissements de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/4316069#titre-bloc-18). Il est possible d&#39;indiquer plusieurs codes régions en les séparant par des virgules.
  # @option opts [String] :code_postal Code postal de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes postaux en les séparant par des virgules.
  # @option opts [String] :convention_collective Convention collective de l&#39;entreprise.
  # @option opts [String] :categorie_juridique Catégorie juridique de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/2028129).   **Note** : Le code correspond à celui de l&#39;INSEE, à l&#39;exception des SASU qui auront comme code 5720 et les EURL qui auront comme code 5498.
  # @option opts [Boolean] :entreprise_cessee Activité de l&#39;entreprise cessée ou non.
  # @option opts [String] :statut_rcs Statut au RCS
  # @option opts [String] :objet_social Objet social de l&#39;entreprise déclaré au RCS.
  # @option opts [String] :date_immatriculation_rcs_min Date d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_immatriculation_rcs_max d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_min Date de radiation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_max Date de radiation au RCS maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :capital_min Capital minimum de l&#39;entreprise.
  # @option opts [String] :capital_max Capital maximum de l&#39;entreprise.
  # @option opts [String] :chiffre_affaires_min Chiffre d&#39;affaires minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :chiffre_affaires_max Chiffre d&#39;affaires maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_min Résultat minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_max Résultat maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :date_creation_min Date de création minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_creation_max Date de création maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :tranche_effectif_min Tranche d&#39;effectifs minimale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :tranche_effectif_max Tranche d&#39;effectifs maximale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :type_dirigeant Type du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :qualite_dirigeant Qualité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :nationalite_dirigeant Nationalité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :prenom_dirigeant Prénom du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_min Âge minimal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_max Âge maximal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_dirigeant_min Date de naissance minimale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_dirigeant_max Date de naissance maximale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [Integer] :age_beneficiaire_min Âge minimal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_beneficiaire_max Âge maximal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_beneficiaire_min Date de naissance minimale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_beneficiaire_max Date de naissance maximale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :nationalite_beneficiaire Nationalité du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_depot_document_min Date de dépôt minimale du document, au format JJ-MM-AAAA.
  # @option opts [Date] :date_depot_document_max Date de dépôt maximale du document, au format JJ-MM-AAAA.
  # @option opts [String] :type_publication Type de publication
  # @option opts [Date] :date_publication_min Date publication minimale de la publication, au format JJ-MM-AAAA.
  # @option opts [Date] :date_publication_max Date de publication maximale de la publication, au format JJ-MM-AAAA.
  # @option opts [String] :siren SIREN de l&#39;entreprise.
  # @return [Recherche200Response]
  describe 'recherche test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for recherche_beneficiaires
  # Recherche les bénéficiaires effectifs qui correspondent à des critères.
  # Tous les paramètres sont optionnels et servent à filtrer la recherche. Les différents bénéficiaires effectifs seront renvoyées dans un tableau &#x60;resultats&#x60;.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :par_page Nombre de résultats affichés sur une page. Valeur par défaut : &#x60;10&#x60;.
  # @option opts [Integer] :page Page de résultats. Valeur par défaut : &#x60;1&#x60;.
  # @option opts [String] :precision Niveau de précision de la recherche. Valeur par défaut : &#x60;\&quot;standard\&quot;&#x60;.
  # @option opts [String] :q Nom et/ou prénom du bénéficiaire effectif.
  # @option opts [Integer] :age_beneficiaire_min Âge minimal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_beneficiaire_max Âge maximal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_beneficiaire_min Date de naissance minimale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_beneficiaire_max Date de naissance maximale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :nationalite_beneficiaire Nationalité du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :code_naf Code NAF de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes NAF en les séparant par des virgules.
  # @option opts [String] :departement Numéro de département de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs départements en les séparant par des virgules.
  # @option opts [String] :region Code de la région de l&#39;un des établissements de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/4316069#titre-bloc-18). Il est possible d&#39;indiquer plusieurs codes régions en les séparant par des virgules.
  # @option opts [String] :code_postal Code postal de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes postaux en les séparant par des virgules.
  # @option opts [String] :convention_collective Convention collective de l&#39;entreprise.
  # @option opts [String] :categorie_juridique Catégorie juridique de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/2028129).   **Note** : Le code correspond à celui de l&#39;INSEE, à l&#39;exception des SASU qui auront comme code 5720 et les EURL qui auront comme code 5498.
  # @option opts [Boolean] :entreprise_cessee Activité de l&#39;entreprise cessée ou non.
  # @option opts [String] :statut_rcs Statut au RCS
  # @option opts [String] :objet_social Objet social de l&#39;entreprise déclaré au RCS.
  # @option opts [String] :date_immatriculation_rcs_min Date d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_immatriculation_rcs_max d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_min Date de radiation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_max Date de radiation au RCS maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :capital_min Capital minimum de l&#39;entreprise.
  # @option opts [String] :capital_max Capital maximum de l&#39;entreprise.
  # @option opts [String] :chiffre_affaires_min Chiffre d&#39;affaires minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :chiffre_affaires_max Chiffre d&#39;affaires maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_min Résultat minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_max Résultat maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :date_creation_min Date de création minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_creation_max Date de création maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :tranche_effectif_min Tranche d&#39;effectifs minimale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :tranche_effectif_max Tranche d&#39;effectifs maximale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :type_dirigeant Type du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :qualite_dirigeant Qualité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :nationalite_dirigeant Nationalité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :prenom_dirigeant Prénom du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_min Âge minimal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_max Âge maximal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_dirigeant_min Date de naissance minimale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_dirigeant_max Date de naissance maximale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [Date] :date_depot_document_min Date de dépôt minimale du document, au format JJ-MM-AAAA.
  # @option opts [Date] :date_depot_document_max Date de dépôt maximale du document, au format JJ-MM-AAAA.
  # @option opts [String] :type_publication Type de publication
  # @option opts [Date] :date_publication_min Date publication minimale de la publication, au format JJ-MM-AAAA.
  # @option opts [Date] :date_publication_max Date de publication maximale de la publication, au format JJ-MM-AAAA.
  # @option opts [String] :siren SIREN de l&#39;entreprise.
  # @return [RechercheBeneficiaires200Response]
  describe 'recherche_beneficiaires test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for recherche_dirigeants
  # Recherche les dirigeants qui correspondent à des critères.
  # Tous les paramètres sont optionnels et servent à filtrer la recherche. Les différents dirigeants seront renvoyées dans un tableau &#x60;resultats&#x60;.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :par_page Nombre de résultats affichés sur une page. Valeur par défaut : &#x60;10&#x60;.
  # @option opts [Integer] :page Page de résultats. Valeur par défaut : &#x60;1&#x60;.
  # @option opts [String] :precision Niveau de précision de la recherche. Valeur par défaut : &#x60;\&quot;standard\&quot;&#x60;.
  # @option opts [String] :q Texte à rechercher. Nom et prénom du dirigeant pour une personne physique, dénomination pour une personne morale.
  # @option opts [String] :type_dirigeant Type du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :qualite_dirigeant Qualité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :nationalite_dirigeant Nationalité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :prenom_dirigeant Prénom du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_min Âge minimal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_max Âge maximal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_dirigeant_min Date de naissance minimale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_dirigeant_max Date de naissance maximale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :code_naf Code NAF de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes NAF en les séparant par des virgules.
  # @option opts [String] :departement Numéro de département de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs départements en les séparant par des virgules.
  # @option opts [String] :region Code de la région de l&#39;un des établissements de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/4316069#titre-bloc-18). Il est possible d&#39;indiquer plusieurs codes régions en les séparant par des virgules.
  # @option opts [String] :code_postal Code postal de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes postaux en les séparant par des virgules.
  # @option opts [String] :convention_collective Convention collective de l&#39;entreprise.
  # @option opts [String] :categorie_juridique Catégorie juridique de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/2028129).   **Note** : Le code correspond à celui de l&#39;INSEE, à l&#39;exception des SASU qui auront comme code 5720 et les EURL qui auront comme code 5498.
  # @option opts [Boolean] :entreprise_cessee Activité de l&#39;entreprise cessée ou non.
  # @option opts [String] :statut_rcs Statut au RCS
  # @option opts [String] :objet_social Objet social de l&#39;entreprise déclaré au RCS.
  # @option opts [String] :date_immatriculation_rcs_min Date d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_immatriculation_rcs_max d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_min Date de radiation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_max Date de radiation au RCS maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :capital_min Capital minimum de l&#39;entreprise.
  # @option opts [String] :capital_max Capital maximum de l&#39;entreprise.
  # @option opts [String] :chiffre_affaires_min Chiffre d&#39;affaires minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :chiffre_affaires_max Chiffre d&#39;affaires maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_min Résultat minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_max Résultat maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :date_creation_min Date de création minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_creation_max Date de création maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :tranche_effectif_min Tranche d&#39;effectifs minimale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :tranche_effectif_max Tranche d&#39;effectifs maximale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [Integer] :age_beneficiaire_min Âge minimal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_beneficiaire_max Âge maximal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_beneficiaire_min Date de naissance minimale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_beneficiaire_max Date de naissance maximale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :nationalite_beneficiaire Nationalité du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_depot_document_min Date de dépôt minimale du document, au format JJ-MM-AAAA.
  # @option opts [Date] :date_depot_document_max Date de dépôt maximale du document, au format JJ-MM-AAAA.
  # @option opts [String] :type_publication Type de publication
  # @option opts [Date] :date_publication_min Date publication minimale de la publication, au format JJ-MM-AAAA.
  # @option opts [Date] :date_publication_max Date de publication maximale de la publication, au format JJ-MM-AAAA.
  # @option opts [String] :siren SIREN de l&#39;entreprise.
  # @return [RechercheDirigeants200Response]
  describe 'recherche_dirigeants test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for recherche_documents
  # Recherche les documents qui correspondent à des critères.
  # Tous les paramètres sont optionnels et servent à filtrer la recherche. Les différents documents seront renvoyées dans un tableau &#x60;resultats&#x60;.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :par_page Nombre de résultats affichés sur une page. Valeur par défaut : &#x60;10&#x60;.
  # @option opts [Integer] :page Page de résultats. Valeur par défaut : &#x60;1&#x60;.
  # @option opts [String] :precision Niveau de précision de la recherche. Valeur par défaut : &#x60;\&quot;standard\&quot;&#x60;.
  # @option opts [String] :q Mot-clé à rechercher dans le contenu du document.
  # @option opts [Date] :date_depot_document_min Date de dépôt minimale du document, au format JJ-MM-AAAA.
  # @option opts [Date] :date_depot_document_max Date de dépôt maximale du document, au format JJ-MM-AAAA.
  # @option opts [String] :code_naf Code NAF de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes NAF en les séparant par des virgules.
  # @option opts [String] :departement Numéro de département de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs départements en les séparant par des virgules.
  # @option opts [String] :region Code de la région de l&#39;un des établissements de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/4316069#titre-bloc-18). Il est possible d&#39;indiquer plusieurs codes régions en les séparant par des virgules.
  # @option opts [String] :code_postal Code postal de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes postaux en les séparant par des virgules.
  # @option opts [String] :convention_collective Convention collective de l&#39;entreprise.
  # @option opts [String] :categorie_juridique Catégorie juridique de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/2028129).   **Note** : Le code correspond à celui de l&#39;INSEE, à l&#39;exception des SASU qui auront comme code 5720 et les EURL qui auront comme code 5498.
  # @option opts [Boolean] :entreprise_cessee Activité de l&#39;entreprise cessée ou non.
  # @option opts [String] :statut_rcs Statut au RCS
  # @option opts [String] :objet_social Objet social de l&#39;entreprise déclaré au RCS.
  # @option opts [String] :date_immatriculation_rcs_min Date d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_immatriculation_rcs_max d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_min Date de radiation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_max Date de radiation au RCS maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :capital_min Capital minimum de l&#39;entreprise.
  # @option opts [String] :capital_max Capital maximum de l&#39;entreprise.
  # @option opts [String] :chiffre_affaires_min Chiffre d&#39;affaires minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :chiffre_affaires_max Chiffre d&#39;affaires maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_min Résultat minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_max Résultat maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :date_creation_min Date de création minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_creation_max Date de création maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :tranche_effectif_min Tranche d&#39;effectifs minimale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :tranche_effectif_max Tranche d&#39;effectifs maximale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :type_dirigeant Type du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :qualite_dirigeant Qualité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :nationalite_dirigeant Nationalité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :prenom_dirigeant Prénom du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_min Âge minimal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_max Âge maximal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_dirigeant_min Date de naissance minimale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_dirigeant_max Date de naissance maximale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [Integer] :age_beneficiaire_min Âge minimal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_beneficiaire_max Âge maximal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_beneficiaire_min Date de naissance minimale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_beneficiaire_max Date de naissance maximale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :nationalite_beneficiaire Nationalité du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :type_publication Type de publication
  # @option opts [Date] :date_publication_min Date publication minimale de la publication, au format JJ-MM-AAAA.
  # @option opts [Date] :date_publication_max Date de publication maximale de la publication, au format JJ-MM-AAAA.
  # @option opts [String] :siren SIREN de l&#39;entreprise.
  # @return [RechercheDocuments200Response]
  describe 'recherche_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for recherche_publications
  # Recherche les publications BODACC qui correspondent à des critères.
  # Tous les paramètres sont optionnels et servent à filtrer la recherche. Les différentes publications seront renvoyées dans un tableau &#x60;resultats&#x60;.
  # @param api_token Clé d&#39;utilisation de l&#39;API
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :par_page Nombre de résultats affichés sur une page. Valeur par défaut : &#x60;10&#x60;.
  # @option opts [Integer] :page Page de résultats. Valeur par défaut : &#x60;1&#x60;.
  # @option opts [String] :precision Niveau de précision de la recherche. Valeur par défaut : &#x60;\&quot;standard\&quot;&#x60;.
  # @option opts [String] :q Mot-clé à rechercher dans le contenu de la publication.
  # @option opts [String] :code_naf Code NAF de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes NAF en les séparant par des virgules.
  # @option opts [String] :departement Numéro de département de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs départements en les séparant par des virgules.
  # @option opts [String] :region Code de la région de l&#39;un des établissements de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/4316069#titre-bloc-18). Il est possible d&#39;indiquer plusieurs codes régions en les séparant par des virgules.
  # @option opts [String] :code_postal Code postal de l&#39;un des établissements de l&#39;entreprise. Il est possible d&#39;indiquer plusieurs codes postaux en les séparant par des virgules.
  # @option opts [String] :convention_collective Convention collective de l&#39;entreprise.
  # @option opts [String] :categorie_juridique Catégorie juridique de l&#39;entreprise, selon la [nomenclature Insee](https://www.insee.fr/fr/information/2028129).   **Note** : Le code correspond à celui de l&#39;INSEE, à l&#39;exception des SASU qui auront comme code 5720 et les EURL qui auront comme code 5498.
  # @option opts [Boolean] :entreprise_cessee Activité de l&#39;entreprise cessée ou non.
  # @option opts [String] :statut_rcs Statut au RCS
  # @option opts [String] :objet_social Objet social de l&#39;entreprise déclaré au RCS.
  # @option opts [String] :date_immatriculation_rcs_min Date d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_immatriculation_rcs_max d&#39;immatriculation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_min Date de radiation au RCS minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_radiation_rcs_max Date de radiation au RCS maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :capital_min Capital minimum de l&#39;entreprise.
  # @option opts [String] :capital_max Capital maximum de l&#39;entreprise.
  # @option opts [String] :chiffre_affaires_min Chiffre d&#39;affaires minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :chiffre_affaires_max Chiffre d&#39;affaires maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_min Résultat minimum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :resultat_max Résultat maximum de l&#39;entreprise.  **Note** : Filtrer sur ce critère restreint énormément les entreprises retournées car cela élimine d&#39;office toutes les entreprises dont les comptes ne sont pas publiés.
  # @option opts [String] :date_creation_min Date de création minimale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :date_creation_max Date de création maximale de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :tranche_effectif_min Tranche d&#39;effectifs minimale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :tranche_effectif_max Tranche d&#39;effectifs maximale de l&#39;entreprise, selon la [nomenclature Sirene](https://www.sirene.fr/sirene/public/variable/tefen).  **Note** : 00 ou NN donneront les mêmes résultats et veulent dire non employeur
  # @option opts [String] :type_dirigeant Type du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :qualite_dirigeant Qualité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :nationalite_dirigeant Nationalité du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [String] :prenom_dirigeant Prénom du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_min Âge minimal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_dirigeant_max Âge maximal du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_dirigeant_min Date de naissance minimale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_dirigeant_max Date de naissance maximale du dirigeant (ou de l&#39;un des dirigeants de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [Integer] :age_beneficiaire_min Âge minimal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Integer] :age_beneficiaire_max Âge maximal du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_de_naissance_beneficiaire_min Date de naissance minimale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises), au format JJ-MM-AAAA.
  # @option opts [Date] :date_de_naissance_beneficiaire_max Date de naissance maximale du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises) de l&#39;entreprise, au format JJ-MM-AAAA.
  # @option opts [String] :nationalite_beneficiaire Nationalité du bénéficiaire effectif (ou de l&#39;un des bénéficiaires effectifs de l&#39;entreprise pour une recherche d&#39;entreprises).
  # @option opts [Date] :date_depot_document_min Date de dépôt minimale du document, au format JJ-MM-AAAA.
  # @option opts [Date] :date_depot_document_max Date de dépôt maximale du document, au format JJ-MM-AAAA.
  # @option opts [String] :type_publication Type de publication
  # @option opts [Date] :date_publication_min Date publication minimale de la publication, au format JJ-MM-AAAA.
  # @option opts [Date] :date_publication_max Date de publication maximale de la publication, au format JJ-MM-AAAA.
  # @option opts [String] :siren SIREN de l&#39;entreprise.
  # @return [RecherchePublications200Response]
  describe 'recherche_publications test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
