=begin
#Pappers API

#L'API de Pappers vous permet de récupérer des informations et documents sur les entreprises françaises à partir de leur numéro SIREN ou SIRET.  Vous devez indiquer votre clé d'API dans les requêtes, en utilisant le paramètre `api_token`.  L'URL d'accès à l'API est https://api.pappers.fr/v2/  Lien vers la documentation de la V1 : https://www.pappers.fr/api/documentation/v1  L'historique des modifications (changelog) est accessible à l'url suivante : https://www.pappers.fr/api/changelog 

The version of the OpenAPI document: 2.7.0
Contact: support@pappers.fr
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.4.0

=end

require 'date'
require 'time'

module OpenapiClient
  class EntrepriseFicheAllOfComptes
    # Date de dépôt des comptes.
    attr_accessor :date_depot

    # Date de dépôt formatée des comptes.
    attr_accessor :date_depot_formate

    # Date de clôture des comptes, au format AAAA-MM-JJ.
    attr_accessor :date_cloture

    # Année de clôture des comptes.
    attr_accessor :annee_cloture

    # Confidentialité totale des comptes.
    attr_accessor :confidentialite

    # Confidentialité partielle des comptes (seul le compte de résultat est confidentiel, le reste des comptes sont disponibles).
    attr_accessor :confidentialite_compte_de_resultat

    # Disponibilité des comptes au format PDF.
    attr_accessor :disponible

    # Nom du fichier PDF des comptes.
    attr_accessor :nom_fichier_pdf

    # Token des comptes.
    attr_accessor :token

    # Disponibilité des comptes au format XLSX.
    attr_accessor :disponible_xlsx

    # Nom du fichier XLSX des comptes.
    attr_accessor :nom_fichier_xlsx

    # Token des comptes XLSX.
    attr_accessor :token_xlsx

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date_depot' => :'date_depot',
        :'date_depot_formate' => :'date_depot_formate',
        :'date_cloture' => :'date_cloture',
        :'annee_cloture' => :'annee_cloture',
        :'confidentialite' => :'confidentialite',
        :'confidentialite_compte_de_resultat' => :'confidentialite_compte_de_resultat',
        :'disponible' => :'disponible',
        :'nom_fichier_pdf' => :'nom_fichier_pdf',
        :'token' => :'token',
        :'disponible_xlsx' => :'disponible_xlsx',
        :'nom_fichier_xlsx' => :'nom_fichier_xlsx',
        :'token_xlsx' => :'token_xlsx'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date_depot' => :'Date',
        :'date_depot_formate' => :'String',
        :'date_cloture' => :'Date',
        :'annee_cloture' => :'Integer',
        :'confidentialite' => :'Boolean',
        :'confidentialite_compte_de_resultat' => :'Boolean',
        :'disponible' => :'Boolean',
        :'nom_fichier_pdf' => :'String',
        :'token' => :'String',
        :'disponible_xlsx' => :'Boolean',
        :'nom_fichier_xlsx' => :'String',
        :'token_xlsx' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `OpenapiClient::EntrepriseFicheAllOfComptes` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `OpenapiClient::EntrepriseFicheAllOfComptes`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date_depot')
        self.date_depot = attributes[:'date_depot']
      end

      if attributes.key?(:'date_depot_formate')
        self.date_depot_formate = attributes[:'date_depot_formate']
      end

      if attributes.key?(:'date_cloture')
        self.date_cloture = attributes[:'date_cloture']
      end

      if attributes.key?(:'annee_cloture')
        self.annee_cloture = attributes[:'annee_cloture']
      end

      if attributes.key?(:'confidentialite')
        self.confidentialite = attributes[:'confidentialite']
      end

      if attributes.key?(:'confidentialite_compte_de_resultat')
        self.confidentialite_compte_de_resultat = attributes[:'confidentialite_compte_de_resultat']
      end

      if attributes.key?(:'disponible')
        self.disponible = attributes[:'disponible']
      end

      if attributes.key?(:'nom_fichier_pdf')
        self.nom_fichier_pdf = attributes[:'nom_fichier_pdf']
      end

      if attributes.key?(:'token')
        self.token = attributes[:'token']
      end

      if attributes.key?(:'disponible_xlsx')
        self.disponible_xlsx = attributes[:'disponible_xlsx']
      end

      if attributes.key?(:'nom_fichier_xlsx')
        self.nom_fichier_xlsx = attributes[:'nom_fichier_xlsx']
      end

      if attributes.key?(:'token_xlsx')
        self.token_xlsx = attributes[:'token_xlsx']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date_depot == o.date_depot &&
          date_depot_formate == o.date_depot_formate &&
          date_cloture == o.date_cloture &&
          annee_cloture == o.annee_cloture &&
          confidentialite == o.confidentialite &&
          confidentialite_compte_de_resultat == o.confidentialite_compte_de_resultat &&
          disponible == o.disponible &&
          nom_fichier_pdf == o.nom_fichier_pdf &&
          token == o.token &&
          disponible_xlsx == o.disponible_xlsx &&
          nom_fichier_xlsx == o.nom_fichier_xlsx &&
          token_xlsx == o.token_xlsx
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date_depot, date_depot_formate, date_cloture, annee_cloture, confidentialite, confidentialite_compte_de_resultat, disponible, nom_fichier_pdf, token, disponible_xlsx, nom_fichier_xlsx, token_xlsx].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = OpenapiClient.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
